defaults: &defaults
  email_server_address: smtp.gmail.com
  email_port: 587
  email_domain: alexsmolen.com
  email_username: nopassword@alexsmolen.com

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
